set(_CATKIN_CURRENT_PACKAGE "aruco_gridboard")
set(aruco_gridboard_VERSION "0.0.1")
set(aruco_gridboard_MAINTAINER "Giovanni Claudio <Giovanni.Claudio@inria.fr>")
set(aruco_gridboard_PACKAGE_FORMAT "1")
set(aruco_gridboard_BUILD_DEPENDS "cv_bridge" "image_geometry" "geometry_msgs" "message_filters" "image_transport" "resource_retriever" "roscpp" "sensor_msgs" "std_msgs")
set(aruco_gridboard_BUILD_EXPORT_DEPENDS "cv_bridge" "image_geometry" "geometry_msgs" "message_filters" "image_transport" "resource_retriever" "roscpp" "sensor_msgs" "std_msgs")
set(aruco_gridboard_BUILDTOOL_DEPENDS "catkin")
set(aruco_gridboard_BUILDTOOL_EXPORT_DEPENDS )
set(aruco_gridboard_EXEC_DEPENDS "cv_bridge" "image_geometry" "geometry_msgs" "message_filters" "image_transport" "resource_retriever" "roscpp" "sensor_msgs" "std_msgs")
set(aruco_gridboard_RUN_DEPENDS "cv_bridge" "image_geometry" "geometry_msgs" "message_filters" "image_transport" "resource_retriever" "roscpp" "sensor_msgs" "std_msgs")
set(aruco_gridboard_TEST_DEPENDS )
set(aruco_gridboard_DOC_DEPENDS )
set(aruco_gridboard_URL_WEBSITE "http://wiki.ros.org/aruco_gridboard")
set(aruco_gridboard_URL_BUGTRACKER "")
set(aruco_gridboard_URL_REPOSITORY "")
set(aruco_gridboard_DEPRECATED "")